name: Recreate OCT image

on:
  # Triggers the workflow every day at 1:17am UTC
  schedule:
    - cron: "17 1 * * *"

  workflow_dispatch:

permissions: read-all

env:
  IMAGE_TAG: latest
  IMAGE_NAME: quay.io/redhat-best-practices-for-k8s/oct
  IMAGE_NAME_LEGACY: quay.io/testnetworkfunction/oct

jobs:
  recreate-oct-container-image:
    if: github.repository_owner == 'redhat-best-practices-for-k8s'
    name: Create new OCT container image
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          token: ${{ secrets.PULL_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Run endpoint verification script
        run: |
          ./scripts/curl-endpoints.sh
      
      - name: Authenticate against Quay.io (redhat-best-practices-for-k8s)
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: quay.io
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USER_K8S }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN_K8S }}

      - name: Build and push the latest images for multi-arch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          build-args: |
            TOKEN=${{ secrets.PULL_TOKEN }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          no-cache: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: If failed to create the image, send alert msg to dev team.
        if: ${{ failure() }}
        uses: ./.github/actions/slack-webhook-sender
        with:
          message: 'Failed to create official latest OCT image. Please check the logs.'
          slack_webhook: '${{ secrets.SLACK_ALERT_WEBHOOK_URL }}'

  recreate-oct-container-image-legacy:
    name: Create new OCT container image (Legacy)
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          token: ${{ secrets.PULL_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Run endpoint verification script
        run: |
          ./scripts/curl-endpoints.sh

      - name: Authenticate against Quay.io (testnetworkfunction)
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: quay.io
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push the latest images for multi-arch (Legacy)
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          build-args: |
            TOKEN=${{ secrets.PULL_TOKEN }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          no-cache: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME_LEGACY }}:${{ env.IMAGE_TAG }}

      - name: If failed to create the image, send alert msg to dev team.
        if: ${{ failure() }}
        uses: ./.github/actions/slack-webhook-sender
        with:
          message: 'Failed to create official latest OCT image. Please check the logs.'
          slack_webhook: '${{ secrets.SLACK_ALERT_WEBHOOK_URL }}'
